### ISSUE TITLE
SUSファイルから 総ノーツ数を取得するエンドポイントが欲しい

### ISSUE THREAD

**Issue by Dosugamea** [PurplePalette/sonolus-sus-server#1]
## どんな機能か
`http://sonolus-sus-server:3000/analyze` に `{"hash": "SusFileHash"}`
を投げたら、S3からSUSファイルを読み出して [sus-js(sus-parse)](https://github.com/mkpoli/sus-js/tree/master/packages/sus-parse) などを使って 譜面情報 + 総ノーツ数を求めて `{"total": 1000, "objects": {"slides": 400, "tap": 400, "flick": 200} }` みたいな感じで返してほしい

## 機能の仕様用途
まず、totalは検索時のソート条件として使われる予定。それ以外は特に予定はないがあったら後で使えるかな程度(めんどくさければなしでOk)

**Comment by sevenc-nanashi** [comment]
`slides` はスライドの数？スライドのコンボ数？

**Comment by sevenc-nanashi** [comment]
あと、`flick` に終点フリックも入れるかとか

**Comment by Dosugamea** [comment]
@sevenc-nanashi 

> スライドの数か、コンボ数か
- スライド要素が何度出現するかっていう個数、つまりスライドをスタートするノーツ(?)が何個あるか

> flick に終点フリックも入れるか
- 入れて良いと思う

**Comment by sevenc-nanashi** [comment]
@Dosugamea 
把握。始点で数えてるので多分仕様通り。
終点フリックは入れた
