### ISSUE TITLE
テストコードの追加

### ISSUE THREAD

**Issue by Dosugamea** [PurplePalette/sonolus-sus-server#4]
他のリポジトリはテストしてるので、これもテストコード作ろう...

**Comment by sevenc-nanashi** [comment]
minio関連をどうするか問題が

**Comment by Dosugamea** [comment]
@sevenc-nanashi 
GithubのCI内でdockerコンテナ動かせるよ
それかsecretにテスト用のS3のアドレスを予め入れておくか
